### ISSUE TITLE
Not working on Ubuntu 20.10

### ISSUE THREAD

**Issue by archetipico** [MasterCruelty/Updater#22] opened 2021-05-20 14:09 UTC
Various problems with this version:
1) Since I already had the alias `up`, I had to first uninstall, then setup again because the alias was marked as already existing (which is true, but the path is different and wasn't updated)
2) Launching up, I can't find `printProgress`, I THINK all the update magic happens, but the program exits before entering the Trash process

I'll go back one commit from my branch and I'll try to obtain the same features from there

**Comment by MasterCruelty** [comment] 2021-05-20 14:34
Ok I already checked and that's true. I'll try to fix as soon as I have the time.
oof

**Comment by MasterCruelty** [comment] 2021-05-20 23:20
Ok this is probably a duplicate of #21 created a couple days ago.
If you confirm we can close this issue and work on the previous one @archetipico

**Comment by archetipico** [comment] 2021-05-21 13:10
It's not an exact duplicate.
`If you launch with up alias ... there is no problem` I have a problem using `up` too.
Since we don't know the source yet, we should mark it as duplicate once we understood what's the problem behind (if the pull request solves both your issue and mine, then this is a duplicate)

**Closed** 2021-06-06 13:09 UTC
Labels: bug, help wanted, high priority
